# Generated by Django 2.1.7 on 2019-04-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_merge_20190403_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
