# Generated by Django 2.1.7 on 2019-04-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_organization_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
