# Generated by Django 2.1.7 on 2019-04-07 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190407_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducatorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['reviewed', '-approved', 'name']},
        ),
        migrations.AddField(
            model_name='educatorrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Organization'),
        ),
        migrations.AddField(
            model_name='educatorrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
