# Generated by Django 2.1.7 on 2019-04-08 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190407_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatorrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educator_request', to='app.Organization'),
        ),
        migrations.AlterField(
            model_name='educatorrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educator_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
