# Generated by Django 2.1.7 on 2019-04-11 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_merge_20190410_1950'),
        ('app', '0023_auto_20190407_2049'),
    ]

    operations = [
    ]
